language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t manavnanwani/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true manavnanwani/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: ""
  app: "docker"
  env: "Docker-env"
  bucket_name: ""
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
